version: '3.8'

services:
  postgres:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_DB: rick_and_morty
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5003:5432'
    volumes:
      - postgres_data_rick:/var/lib/postgresql/data

  backend:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - type: bind
        source: .
        target: /app
        consistency: delegated

volumes:
  postgres_data_rick:
